inkscape drawing2.svg -D --export-type png -w 72 -h 72 -o ic_launcher\res\mipmap-hdpi\ic_launcher.png
inkscape drawing2.svg -D --export-type png -w 512 -h 512 -o ic_launcher\res\mipmap-hdpi\background.png
inkscape drawing2.svg -D --export-type png -w 48 -h 48 -o ic_launcher\res\mipmap-mdpi\ic_launcher.png
inkscape drawing2.svg -D --export-type png -w 512 -h 512 -o ic_launcher\res\mipmap-mdpi\background.png
inkscape drawing2.svg -D --export-type png -w 96 -h 96 -o ic_launcher\res\mipmap-xhdpi\ic_launcher.png
inkscape drawing2.svg -D --export-type png -w 512 -h 512 -o ic_launcher\res\mipmap-xhdpi\background.png
inkscape drawing2.svg -D --export-type png -w 144 -h 144 -o ic_launcher\res\mipmap-xxhdpi\ic_launcher.png
inkscape drawing2.svg -D --export-type png -w 512 -h 512 -o ic_launcher\res\mipmap-xxhdpi\background.png
inkscape drawing2.svg -D --export-type png -w 192 -h 192 -o ic_launcher\res\mipmap-xxxhdpi\ic_launcher.png
inkscape drawing2.svg -D --export-type png -w 512 -h 512 -o ic_launcher\res\mipmap-xxxhdpi\background.png
